# This workflow will build and push a new container image to Amazon ECR,
name: Deploy to Amazon ECS

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden    
  
# env:
#   AWS_REGION: ${{ secrets.VINOD_TEST }}                 # set this to your preferred AWS region, e.g. us-west-1
#   UAT: ${{ secrets.VINOD_DEV }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build, tag, and push image to Amazon ECR
      env:
         VINOD_DEV: ${{ secrets.VINOD_DEV }}
      run: |
        echo "organization: ${{ secrets.VINOD_TEST }}"
        echo "environment: ${{ secrets.VINOD_DEV }}"

