# This workflow will build and push a new container image to Amazon ECR,
name: Deploy to Amazon ECS

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden    
  
# env:
#   AWS_REGION: ${{ secrets.VINOD_TEST }}                 # set this to your preferred AWS region, e.g. us-west-1
#   UAT: ${{ secrets.VINOD_DEV }}
#echo "organization: ${{ secrets.VINOD_TEST }}"
#]echo "environment: ${{ env.VINOD_DEV }}"
jobs:
  deploy:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - name: Build, tag, and push image to Amazon ECR
      env:
         VINOD_DEV: ${{ secrets.VINOD_DEV }}
      run: VINOD_DEV=${{ env.VINOD_DEV }}


